[package]
name = "tior"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.8", features = ["derive"] }
crossterm = { version = "0.27.0" }
inquire = "0.6.2"
log = "0.4.20"
pretty_env_logger = "0.5.0"
serde = { version = "1.0.192", features = ["derive"] }
serialport = { version = "4.2.2" }
